nginx:
  build: ./nginx/
  ports:
    - 80:80
  links:
    - php
  volumes_from:
    - app

php:
  build:  ./php/
  environment:
    XDEBUG_CONFIG: remote_host=192.168.99.1
  expose: 
    - 9000
  links:
      - mysql
  volumes_from:
    - app

app:
  image: php:5.6-fpm
  volumes:
    - ./www:/var/www/html
  command: "true"

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
    - 8080:80
  links:
    - mysql
  environment:
    PMA_HOST: mysql


mysql:
  image: mysql:latest
  ports:
    - 3306:3306
  volumes_from:
    - data
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: magento
    MYSQL_USER: root
    MYSQL_PASSWORD: root

data:
    image: mysql:latest
    volumes: 
      - /var/lib/mysql
    command: "true"

